import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = parseInt(process.env.SMTP_PORT || '587', 10);
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;

let transporter: nodemailer.Transporter | null = null;

// Initialize transport if credentials are set
if (SMTP_HOST && SMTP_USER && SMTP_PASS) {
  transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465, // true for 465, false for other ports
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });
  console.log(`✉️ Mailer initialized. SMTP Host: ${SMTP_HOST}:${SMTP_PORT}`);
} else {
  console.warn('⚠️  MAILER WARNING: SMTP_HOST, SMTP_USER, or SMTP_PASS not set in backend/.env!');
  console.log('💡 Invitations will fall back to terminal console logs only.');
}

interface SendInviteMailOptions {
  toEmail: string;
  workspaceName: string;
  inviterName: string;
  inviteLink: string;
}

/**
 * Sends a real invitation email via SMTP if configured, otherwise falls back to logging
 */
export async function sendInvitationEmail(options: SendInviteMailOptions): Promise<boolean> {
  const { toEmail, workspaceName, inviterName, inviteLink } = options;

  const htmlContent = `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 24px; max-width: 600px; margin: auto; border: 1px solid #e7f0fe; rounded: 16px; background-color: #f3f8ff;">
      <h2 style="color: #1d4ed8; font-weight: 800;">Workspace Invitation</h2>
      <p style="font-size: 14px; color: #132242; line-height: 1.6;">
        Hello,
      </p>
      <p style="font-size: 14px; color: #132242; line-height: 1.6;">
        You have been invited to join the <strong>${workspaceName}</strong> Workspace by <strong>${inviterName}</strong>. 
      </p>
      <div style="margin: 24px 0; text-align: center;">
        <a href="${inviteLink}" style="background: linear-gradient(135deg, #2563eb, #1d4ed8); color: white; padding: 12px 24px; border-radius: 8px; font-weight: bold; text-decoration: none; display: inline-block; font-size: 14px; box-shadow: 0 4px 6px rgba(37,99,235,0.15);">
          Join Workspace
        </a>
      </div>
      <p style="font-size: 12px; color: #5b6b8c; line-height: 1.6;">
        If the button above does not work, copy and paste this link into your web browser:
      </p>
      <p style="font-size: 11px; word-break: break-all; color: #2563eb; background-color: white; padding: 10px; border-radius: 6px; border: 1px solid #dbe6fb;">
        ${inviteLink}
      </p>
      <hr style="border: 0; border-top: 1px solid #dbe6fb; margin-top: 24px;">
      <p style="font-size: 11px; color: #5b6b8c; text-align: center; margin-top: 12px;">
        This email was automatically generated by Magadige Todo Calendar.
      </p>
    </div>
  `;

  const textContent = `
    Workspace Invitation
    
    You have been invited to join the ${workspaceName} Workspace by ${inviterName}.
    
    Click the link below to join and access the workspace:
    ${inviteLink}
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from: `"Magadige Todo" <${SMTP_USER}>`,
        to: toEmail,
        subject: `You've been invited to join the ${workspaceName} Workspace`,
        text: textContent,
        html: htmlContent,
      });
      console.log(`✉️  Invitation email successfully sent to ${toEmail}`);
      return true;
    } catch (error: any) {
      console.error(`❌ Failed to send invitation email via SMTP to ${toEmail}:`, error.message);
      return false;
    }
  } else {
    // Console fallback
    return false;
  }
}
