import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = parseInt(process.env.SMTP_PORT || '587', 10);
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;

let transporter: nodemailer.Transporter | null = null;

// Initialize transport if credentials are set
if (SMTP_HOST && SMTP_USER && SMTP_PASS) {
  transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465, // true for 465, false for other ports
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });
  console.log(`✉️ Mailer initialized. SMTP Host: ${SMTP_HOST}:${SMTP_PORT}`);
} else {
  console.warn('⚠️  MAILER WARNING: SMTP_HOST, SMTP_USER, or SMTP_PASS not set in backend/.env!');
  console.log('💡 Invitations will fall back to terminal console logs only.');
}

interface SendInviteMailOptions {
  toEmail: string;
  workspaceName: string;
  inviterName: string;
  inviteLink: string;
}

/**
 * Sends a real invitation email via SMTP if configured, otherwise falls back to logging
 */
export async function sendInvitationEmail(options: SendInviteMailOptions): Promise<boolean> {
  const { toEmail, workspaceName, inviterName, inviteLink } = options;

  const htmlContent = `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 24px; max-width: 600px; margin: auto; border: 1px solid #e7f0fe; rounded: 16px; background-color: #f3f8ff;">
      <h2 style="color: #1d4ed8; font-weight: 800;">Workspace Invitation</h2>
      <p style="font-size: 14px; color: #132242; line-height: 1.6;">
        Hello,
      </p>
      <p style="font-size: 14px; color: #132242; line-height: 1.6;">
        You have been invited to join the <strong>${workspaceName}</strong> Workspace by <strong>${inviterName}</strong>. 
      </p>
      <div style="margin: 24px 0; text-align: center;">
        <a href="${inviteLink}" style="background: linear-gradient(135deg, #2563eb, #1d4ed8); color: white; padding: 12px 24px; border-radius: 8px; font-weight: bold; text-decoration: none; display: inline-block; font-size: 14px; box-shadow: 0 4px 6px rgba(37,99,235,0.15);">
          Join Workspace
        </a>
      </div>
      <p style="font-size: 12px; color: #5b6b8c; line-height: 1.6;">
        If the button above does not work, copy and paste this link into your web browser:
      </p>
      <p style="font-size: 11px; word-break: break-all; color: #2563eb; background-color: white; padding: 10px; border-radius: 6px; border: 1px solid #dbe6fb;">
        ${inviteLink}
      </p>
      <hr style="border: 0; border-top: 1px solid #dbe6fb; margin-top: 24px;">
      <p style="font-size: 11px; color: #5b6b8c; text-align: center; margin-top: 12px;">
        This email was automatically generated by Magadige Todo Calendar.
      </p>
    </div>
  `;

  const textContent = `
    Workspace Invitation
    
    You have been invited to join the ${workspaceName} Workspace by ${inviterName}.
    
    Click the link below to join and access the workspace:
    ${inviteLink}
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from: `"Magadige Todo" <${SMTP_USER}>`,
        to: toEmail,
        subject: `You've been invited to join the ${workspaceName} Workspace`,
        text: textContent,
        html: htmlContent,
      });
      console.log(`✉️  Invitation email successfully sent to ${toEmail}`);
      return true;
    } catch (error: any) {
      console.error(`❌ Failed to send invitation email via SMTP to ${toEmail}:`, error.message);
      return false;
    }
  } else {
    // Console fallback
    return false;
  }
}

interface TaskAssignmentOptions {
  toEmail: string;
  workspaceName: string;
  taskName: string;
  dueDate: string;
  dueTime: string;
  priority: string;
  inviterName: string;
}

/**
 * Sends a real task assignment email via SMTP if configured
 */
export async function sendTaskAssignmentEmail(options: TaskAssignmentOptions): Promise<boolean> {
  const { toEmail, workspaceName, taskName, dueDate, dueTime, priority, inviterName } = options;

  const htmlContent = `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 24px; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.03);">
      <h2 style="color: #2563eb; font-weight: 800; font-size: 20px; border-bottom: 2px solid #eff6ff; padding-bottom: 12px; margin-top: 0;">📋 New Task Assigned</h2>
      <p style="font-size: 14px; color: #1e293b; line-height: 1.6;">
        Hello,
      </p>
      <p style="font-size: 14px; color: #1e293b; line-height: 1.6;">
        You have been assigned a new task in the workspace <strong>${workspaceName}</strong> by <strong>${inviterName}</strong>.
      </p>
      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin: 20px 0;">
        <h3 style="margin: 0 0 10px 0; color: #0f172a; font-size: 16px; font-weight: 700;">${taskName}</h3>
        <p style="margin: 4px 0; font-size: 13px; color: #475569;">📅 <strong>Due Date:</strong> ${dueDate || 'No date'}</p>
        <p style="margin: 4px 0; font-size: 13px; color: #475569;">⏰ <strong>Due Time:</strong> ${dueTime || 'No time'}</p>
        <p style="margin: 4px 0; font-size: 13px; color: #475569;">🔥 <strong>Priority:</strong> ${priority || 'Normal'}</p>
      </div>
      <p style="font-size: 12px; color: #64748b; line-height: 1.6;">
        Please log into your dashboard and check the Workspace section to start working on this task.
      </p>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 24px;">
      <p style="font-size: 11px; color: #94a3b8; text-align: center; margin-top: 12px;">
        This email was automatically generated by Magadige Todo Calendar.
      </p>
    </div>
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from: `"Magadige Todo" <${SMTP_USER}>`,
        to: toEmail,
        subject: `[Task Assigned] ${taskName}`,
        text: `You have been assigned a new task: ${taskName} in Workspace ${workspaceName}.`,
        html: htmlContent,
      });
      console.log(`✉️  Task assignment email successfully sent to ${toEmail}`);
      return true;
    } catch (error: any) {
      console.error(`❌ Failed to send task assignment email via SMTP to ${toEmail}:`, error.message);
      return false;
    }
  }
  return false;
}

interface TaskCompletionOptions {
  ownerEmail: string;
  workspaceName: string;
  taskName: string;
  assigneeEmail: string;
}

/**
 * Sends a real task completion email via SMTP if configured
 */
export async function sendTaskCompletionEmail(options: TaskCompletionOptions): Promise<boolean> {
  const { ownerEmail, workspaceName, taskName, assigneeEmail } = options;

  const htmlContent = `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 24px; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.03);">
      <h2 style="color: #16a34a; font-weight: 800; font-size: 20px; border-bottom: 2px solid #f0fdf4; padding-bottom: 12px; margin-top: 0;">✔️ Task Completed</h2>
      <p style="font-size: 14px; color: #1e293b; line-height: 1.6;">
        Hello,
      </p>
      <p style="font-size: 14px; color: #1e293b; line-height: 1.6;">
        Great news! The task <strong>${taskName}</strong> in your workspace <strong>${workspaceName}</strong> has been marked as <strong>Completed</strong> by <strong>${assigneeEmail}</strong>.
      </p>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 24px;">
      <p style="font-size: 11px; color: #94a3b8; text-align: center; margin-top: 12px;">
        This email was automatically generated by Magadige Todo Calendar.
      </p>
    </div>
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from: `"Magadige Todo" <${SMTP_USER}>`,
        to: ownerEmail,
        subject: `[Task Completed] ${taskName}`,
        text: `${assigneeEmail} has completed the task: ${taskName} in Workspace ${workspaceName}.`,
        html: htmlContent,
      });
      console.log(`✉️  Task completion email successfully sent to ${ownerEmail}`);
      return true;
    } catch (error: any) {
      console.error(`❌ Failed to send task completion email via SMTP to ${ownerEmail}:`, error.message);
      return false;
    }
  }
  return false;
}
